; [api_endpoints]
; base_url = ${BASE_URL}
; jd_analyze = ${base_url}/jd-analyze

; generate_cover_letter = ${base_url}/generate/cover-letter
; generate_email = ${base_url}/generate/email
; generate_outreach_message = ${base_url}/generate/outreach-message
; run_full_pipeline = ${base_url}/run-full-pipeline
; resume_scan =  ${base_url}/resume/scan
; resume_fallback = ${base_url}/resume/fallback
; resume_compile =  ${base_url}/resume/compile
; update_resume = ${base_url}/resume/update
; export_resume = ${base_url}/resume/export

[gemini_api]
api_key1 = ${GEMINI_API_KEY1} 
api_key2= ${GEMINI_API_KEY2}
model = ${GEMINI_MODEL}
temperature = ${GEMINI_TEMPERATURE}

[openai_api]
api_key = ${OPENAI_API_KEY}
model= ${OPENAI_MODEL}
temperature=${OPENAI_TEMPERATURE}

[path_dir]
base_dir = ${BASE_DIR}
data_dir = ${BASE_DIR}/data

[rag_config]
embedding_model=all-mpnet-base-v2

[sqlite]
sql_path = ${BASE_DIR}/data/app.db
chroma_path = ${BASE_DIR}/data/vectorstore/chroma.sqlite3

[huggingface]
token = ${HUGGING_FACE_TOKEN}